In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv("../dataset/cleaned/zomato_cleaned.csv")
df.head()
df.shape
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 41226 entries, 0 to 41225
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         41226 non-null  str
 1   online_order                 41226 non-null  str
 2   book_table                   41226 non-null  str
 3   rate                         41226 non-null  float64
 4   votes                        41226 non-null  int64
 5   location                     41226 non-null  str
 6   rest_type                    41226 non-null  str
 7   cuisines                     41226 non-null  str
 8   approx_cost(for two people)  41226 non-null  float64
 9   reviews_list                 41226 non-null  str
 10  menu_item                    41226 non-null  str
 11  listed_in(type)              41226 non-null  str
 12  listed_in(city)              41226 non-null  str
dtypes: float64(2), int64(1), str(10)
memory usage: 4.1 MB

In [2]:
features=[
    "name",
    "cuisines",
    "rest_type",
    "location",
    "rate",
    "votes",
    "approx_cost(for two people)"
]
df=df[features]

In [3]:
df.head()
df.shape

(41226, 7)

In [4]:
text_columns=[
    "cuisines",
    "rest_type",
    "location"
]

In [5]:
for col in text_columns:
    df[col]=df[col].str.lower()

In [6]:
for col in text_columns:
    df[col]=df[col].str.strip()

In [7]:
df.head()

,name,cuisines,rest_type,location,rate,votes,approx_cost(for two people)
0,Jalsa,"north indian, mughlai, chinese",casual dining,banashankari,4.1,775,800.0
1,Spice Elephant,"chinese, north indian, thai",casual dining,banashankari,4.1,787,800.0
2,San Churro Cafe,"cafe, mexican, italian","cafe, casual dining",banashankari,3.8,918,800.0
3,Addhuri Udupi Bhojana,"south indian, north indian",quick bites,banashankari,3.7,88,300.0
4,Grand Village,"north indian, rajasthani",casual dining,basavanagudi,3.8,166,600.0

In [8]:
df["restaurant_profile"]=(
    df["cuisines"]
    +" "
    + df["rest_type"]
    +" "
    + df["location"]
)

In [9]:
df[["name","restaurant_profile"]].head(10)

,name,restaurant_profile
0,Jalsa,"north indian, mughlai, chinese casual dining b..."
1,Spice Elephant,"chinese, north indian, thai casual dining bana..."
2,San Churro Cafe,"cafe, mexican, italian cafe, casual dining ban..."
3,Addhuri Udupi Bhojana,"south indian, north indian quick bites banasha..."
4,Grand Village,"north indian, rajasthani casual dining basavan..."
5,Timepass Dinner,north indian casual dining basavanagudi
6,Rosewood International Hotel - Bar & Restaurant,"north indian, south indian, andhra, chinese ca..."
7,Onesta,"pizza, cafe, italian casual dining, cafe banas..."
8,Penthouse Cafe,"cafe, italian, continental cafe banashankari"
9,Smacznego,"cafe, mexican, italian, momos, beverages cafe ..."

In [10]:
df["restaurant_profile"].isnull().sum()
df["restaurant_profile"].iloc[0]

'north indian, mughlai, chinese casual dining banashankari'

In [11]:
import os
os.makedirs("../dataset/engineered",exist_ok=True)

In [12]:
df.to_csv(
    "../dataset/engineered/zomato_engineered.csv",
    index=False
)

In [13]:
engineered_df=pd.read_csv(
    "../dataset/engineered/zomato_engineered.csv"
)

In [14]:
engineered_df.head()
engineered_df.shape

(41226, 8)

In [15]:
df.isnull().sum()

name                           0
cuisines                       0
rest_type                      0
location                       0
rate                           0
votes                          0
approx_cost(for two people)    0
restaurant_profile             0
dtype: int64

In [16]:
df.shape

(41226, 8)

In [17]:
import os

os.makedirs("../dataset/engineered", exist_ok=True)

df.to_csv(
    "../dataset/engineered/zomato_engineered.csv",
    index=False
)

In [18]:
bad_text=df[df["name"].astype(str).str.contains("Ã|Â|â",regex=True,na=False)]
bad_text[["name"]].head(20)

                                                   name
10    CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Down The A...
159   CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Down The A...
492   CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Down The A...
827     Bohra Bohra CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ©
1425   E2 - EntrÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ©e Envoy
1430     Cocoa 'n' CrÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¨me
1529     Cocoa 'n' CrÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¨me
3296        Foreign CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ©
3497              PiÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ±ata
3521  Mint Spice CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ©...
3598              PiÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ±ata
3699  Mint Spice CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ©...
4033          CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Felix
4044        CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Mor'ish
4048  Urban Solace - CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂ...
4057          CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© MH-28
4059           WAFL CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ©
4061  The CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© @ Saanchi
4063   Moto Store & CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ©
4107   Moto Store & CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ©

In [19]:
def fix_encoding(text):
    if pd.isna(text):
        return text
    text=str(text)
    try:
        return text.encode("latin1").decode("utf-8")
    except (UnicodeEncodeError, UnicodeDecodeError):
        return text

In [20]:
text_columns=[
    "name",
    "cuisines",
    "rest_type",
    "location",
    "restaurant_profile"
]
for column in text_columns:
    if column in df.columns:
        df[column]=df[column].apply(fix_encoding)

In [21]:
df[df["name"].astype(str).str.contains("Caf|Solace",case=False,na=False)][["name"]].head(20)

                                   name
2                       San Churro Cafe
8                        Penthouse Cafe
10   CafÃÂÃÂÃÂÃÂ© Down The Alley
11                         Cafe Shuffle
13                           Caf-Eleven
14                      San Churro Cafe
15                        Cafe Vivacity
18                             T3H Cafe
19        360 Atoms Restaurant And Cafe
20                     The Vintage Cafe
22                      Cafe Coffee Day
24                        Hide Out Cafe
25                            CAFE NOVA
27                       Sea Green Cafe
29                     Srinathji's Cafe
71                     The Biryani Cafe
72                             LSD Cafe
98                            CAFE NOVA
150                       Calcutta Cafe
159  CafÃÂÃÂÃÂÃÂ© Down The Alley

In [22]:
df.shape

(41226, 8)

In [23]:
# Inspect the corrupted restaurant name exactly
bad_names = df[
    df["name"].astype(str).str.contains("Ã|Â|â", regex=True, na=False)
]["name"]

for name in bad_names.head(10):
    print(repr(name))

'CafÃ\x83Â\x83Ã\x82Â\x83Ã\x83Â\x82Ã\x82Â© Down The Alley'
'CafÃ\x83Â\x83Ã\x82Â\x83Ã\x83Â\x82Ã\x82Â© Down The Alley'
'CafÃ\x83Â\x83Ã\x82Â\x83Ã\x83Â\x82Ã\x82Â© Down The Alley'
'Bohra Bohra CafÃ\x83Â\x83Ã\x82Â\x83Ã\x83Â\x82Ã\x82Â©'
'E2 - EntrÃ\x83Â\x83Ã\x82Â\x83Ã\x83Â\x82Ã\x82Â©e Envoy'
"Cocoa 'n' CrÃ\x83Â\x83Ã\x82Â\x83Ã\x83Â\x82Ã\x82Â¨me"
"Cocoa 'n' CrÃ\x83Â\x83Ã\x82Â\x83Ã\x83Â\x82Ã\x82Â¨me"
'Foreign CafÃ\x83Â\x83Ã\x82Â\x83Ã\x83Â\x82Ã\x82Â©'
'PiÃ\x83Â\x83Ã\x82Â\x83Ã\x83Â\x82Ã\x82Â±ata'
'Mint Spice CafÃ\x83Â\x83Ã\x82Â\x83Ã\x83Â\x82Ã\x82Â© & Restaurant'

In [24]:
print(bad_names.head(10).tolist())

['CafÃ\x83Â\x83Ã\x82Â\x83Ã\x83Â\x82Ã\x82Â© Down The Alley', 'CafÃ\x83Â\x83Ã\x82Â\x83Ã\x83Â\x82Ã\x82Â© Down The Alley', 'CafÃ\x83Â\x83Ã\x82Â\x83Ã\x83Â\x82Ã\x82Â© Down The Alley', 'Bohra Bohra CafÃ\x83Â\x83Ã\x82Â\x83Ã\x83Â\x82Ã\x82Â©', 'E2 - EntrÃ\x83Â\x83Ã\x82Â\x83Ã\x83Â\x82Ã\x82Â©e Envoy', "Cocoa 'n' CrÃ\x83Â\x83Ã\x82Â\x83Ã\x83Â\x82Ã\x82Â¨me", "Cocoa 'n' CrÃ\x83Â\x83Ã\x82Â\x83Ã\x83Â\x82Ã\x82Â¨me", 'Foreign CafÃ\x83Â\x83Ã\x82Â\x83Ã\x83Â\x82Ã\x82Â©', 'PiÃ\x83Â\x83Ã\x82Â\x83Ã\x83Â\x82Ã\x82Â±ata', 'Mint Spice CafÃ\x83Â\x83Ã\x82Â\x83Ã\x83Â\x82Ã\x82Â© & Restaurant']

In [25]:
def fix_multiple_encoding(text, max_attempts=5):
    if pd.isna(text):
        return text

    text = str(text)

    for _ in range(max_attempts):
        try:
            fixed = text.encode("latin1").decode("utf-8")

            # Stop if another conversion doesn't change anything
            if fixed == text:
                break

            text = fixed

        except (UnicodeEncodeError, UnicodeDecodeError):
            break

    return text

In [26]:
text_columns = [
    "name",
    "cuisines",
    "rest_type",
    "location",
    "restaurant_profile"
]

for column in text_columns:
    if column in df.columns:
        df[column] = df[column].apply(fix_multiple_encoding)

In [27]:
bad_names = df[
    df["name"].astype(str).str.contains("Ã|Â|â", regex=True, na=False)
]["name"]

for name in bad_names.head(20):
    print(repr(name))

'Yauatcha Pâtisserie'
'Yauatcha Pâtisserie'
'Yauatcha Pâtisserie'
'Yauatcha Pâtisserie'
'Yauatcha Pâtisserie'
'Yauatcha Pâtisserie'
'Yauatcha Pâtisserie'
'Yauatcha Pâtisserie'
'Yauatcha Pâtisserie'
'Yauatcha Pâtisserie'
'Moto Store & CafÃ©'
'WAFL CafÃ©'
"CafÃ© Mor'ish"
'Yauatcha PÃ¢tisserie'
'CafÃ© MH-28'
'Urban Solace - CafÃ© for the Soul'
'CafÃ© Felix'
'Le ChÃ©ri'
'Yauatcha Pâtisserie'
'Yauatcha Pâtisserie'

In [28]:
df[df["name"].str.contains("Caf", case=False, na=False)][["name"]].head(20)

                              name
2                  San Churro Cafe
8                   Penthouse Cafe
10             Café Down The Alley
11                    Cafe Shuffle
13                      Caf-Eleven
14                 San Churro Cafe
15                   Cafe Vivacity
18                        T3H Cafe
19   360 Atoms Restaurant And Cafe
20                The Vintage Cafe
22                 Cafe Coffee Day
24                   Hide Out Cafe
25                       CAFE NOVA
27                  Sea Green Cafe
29                Srinathji's Cafe
71                The Biryani Cafe
72                        LSD Cafe
98                       CAFE NOVA
150                  Calcutta Cafe
159            Café Down The Alley

In [29]:
# Check only for common mojibake patterns
bad_names = df[
    df["name"].astype(str).str.contains(
        r"Ã|Â|â€|â€™|â€œ|â€“|â€”|ðŸ",
        regex=True,
        na=False
    )
]["name"]

for name in bad_names.head(20):
    print(repr(name))

'Moto Store & CafÃ©'
'WAFL CafÃ©'
"CafÃ© Mor'ish"
'Yauatcha PÃ¢tisserie'
'CafÃ© MH-28'
'Urban Solace - CafÃ© for the Soul'
'CafÃ© Felix'
'Le ChÃ©ri'

In [30]:
for column in text_columns:
    bad = df[
        df[column].astype(str).str.contains(
            r"Ã|Â|â€|â€™|â€œ|â€“|â€”|ðŸ",
            regex=True,
            na=False
        )
    ]

    print(f"\n{column}: {len(bad)} suspicious rows")

name: 8 suspicious rows

cuisines: 0 suspicious rows

rest_type: 0 suspicious rows

location: 0 suspicious rows

restaurant_profile: 0 suspicious rows

In [31]:
# Fix the remaining corrupted restaurant names

df["name"] = df["name"].apply(fix_multiple_encoding)

In [32]:
bad_names = df[
    df["name"].astype(str).str.contains(
        r"Ã|Â|â€|â€™|â€œ|â€“|â€”|ðŸ",
        regex=True,
        na=False
    )
]["name"]

print(f"Remaining corrupted names: {len(bad_names)}")

for name in bad_names:
    print(repr(name))

Remaining corrupted names: 0

In [33]:
df[
    df["name"].str.contains(
        "Café|Chéri|Mor'ish",
        case=False,
        na=False
    )
][["name"]].head(20)

                                  name
10                 Café Down The Alley
159                Café Down The Alley
492                Café Down The Alley
827                   Bohra Bohra Café
3296                      Foreign Café
3521      Mint Spice Café & Restaurant
3699      Mint Spice Café & Restaurant
4033                        Café Felix
4044                      Café Mor'ish
4048  Urban Solace - Café for the Soul
4057                        Café MH-28
4059                         WAFL Café
4061                The Café @ Saanchi
4063                 Moto Store & Café
4107                 Moto Store & Café
4205                         WAFL Café
4296                      Foreign Café
4321                      Café Mor'ish
4427                        Café MH-28
4446  Urban Solace - Café for the Soul

In [34]:
df["combined_text"] = (
    df["name"].fillna("") + " " +
    df["cuisines"].fillna("") + " " +
    df["rest_type"].fillna("") + " " +
    df["location"].fillna("") + " " +
    df["restaurant_profile"].fillna("")
)

In [35]:
df[["name", "combined_text"]].head()

                    name                                      combined_text
0                  Jalsa  Jalsa north indian, mughlai, chinese casual di...
1         Spice Elephant  Spice Elephant chinese, north indian, thai cas...
2        San Churro Cafe  San Churro Cafe cafe, mexican, italian cafe, c...
3  Addhuri Udupi Bhojana  Addhuri Udupi Bhojana south indian, north indi...
4          Grand Village  Grand Village north indian, rajasthani casual ...

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    stop_words="english",
    max_features=5000
)

tfidf_matrix = tfidf.fit_transform(df["combined_text"])

print("TF-IDF shape:", tfidf_matrix.shape)

TF-IDF shape: (41226, 5000)

In [37]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_sim = cosine_similarity(tfidf_matrix)

print("Similarity matrix shape:", cosine_sim.shape)

Similarity matrix shape: (41226, 41226)

In [38]:
indices = pd.Series(
    df.index,
    index=df["name"].str.lower()
).drop_duplicates()

print(indices.head())

name
jalsa                    0
spice elephant           1
san churro cafe          2
addhuri udupi bhojana    3
grand village            4
dtype: int64

In [40]:
restaurant = "Jalsa"
matches = df.index[
    df["name"].str.lower() == restaurant.lower()
]
print("Matching rows:", len(matches))
idx = int(matches[0])

# Get similarity scores for that restaurant
similarity_scores = cosine_sim[idx].ravel()

# Create (index, score) pairs
similarity_scores = list(enumerate(similarity_scores))

# Sort by similarity
similarity_scores = sorted(
    similarity_scores,
    key=lambda x: float(x[1]),
    reverse=True
)

# Display top 10
for i, score in similarity_scores[:10]:
    print(df.loc[i, "name"], round(float(score), 4))

Matching rows: 11
Jalsa 1.0
Jalsa 1.0
Jalsa 1.0
Jalsa 1.0
Jalsa 1.0
Jalsa 1.0
Jalsa 1.0
Jalsa 1.0
Jalsa 1.0
Food Box Cafe 0.7967

In [41]:
restaurant = "Jalsa"

matches = df.index[
    df["name"].str.lower() == restaurant.lower()
]

idx = int(matches[0])

similarity_scores = cosine_sim[idx].ravel()

similarity_scores = [
    (i, float(score))
    for i, score in enumerate(similarity_scores)
    if df.loc[i, "name"].lower() != restaurant.lower()
]

similarity_scores = sorted(
    similarity_scores,
    key=lambda x: x[1],
    reverse=True
)

for i, score in similarity_scores[:10]:
    print(
        df.loc[i, "name"],
        "| similarity:",
        round(score, 4)
    )

Food Box Cafe | similarity: 0.7967
J Spice | similarity: 0.6756
J Spice | similarity: 0.6756
J Spice | similarity: 0.6756
J Spice | similarity: 0.6756
J Spice | similarity: 0.6756
J Spice | similarity: 0.6756
1947 | similarity: 0.6142
1947 | similarity: 0.6142
New Imperial Restaurant | similarity: 0.5932

In [42]:
# Get similar restaurants
restaurant = "Jalsa"

matches = df.index[
    df["name"].str.lower() == restaurant.lower()
]

idx = int(matches[0])

similarity_scores = cosine_sim[idx].ravel()

recommendations = pd.DataFrame({
    "index": range(len(df)),
    "similarity_score": similarity_scores
})

# Add restaurant information
recommendations["name"] = df["name"].values
recommendations["cuisines"] = df["cuisines"].values
recommendations["location"] = df["location"].values
recommendations["rate"] = df["rate"].values
recommendations["votes"] = df["votes"].values

# Remove the input restaurant itself
recommendations = recommendations[
    recommendations["name"].str.lower() != restaurant.lower()
]

# Sort by similarity
recommendations = recommendations.sort_values(
    "similarity_score",
    ascending=False
)

# Keep only one row per restaurant
recommendations = recommendations.drop_duplicates(
    subset=["name"],
    keep="first"
)

recommendations.head(10)

,index,similarity_score,name,cuisines,location,rate,votes
533,533,0.796713,Food Box Cafe,"mughlai, north indian, chinese",banashankari,3.6,36
527,527,0.675647,J Spice,"north indian, chinese",banashankari,3.8,59
63,63,0.614198,1947,"north indian, chinese",banashankari,4.0,808
18704,18704,0.593170,New Imperial Restaurant,"north indian, chinese",banashankari,3.7,39
304,304,0.591951,Sri Krishna Sagar,"north indian, chinese",banashankari,3.2,119
217,217,0.589168,Green Gardenia,"north indian, chinese",banashankari,3.8,160
33045,33045,0.585030,Jalsa Gold,"north indian, mughlai, italian",marathahalli,4.5,3486
175,175,0.558474,Thamboola,"north indian, chinese, continental",banashankari,3.9,135
538,538,0.543986,Manifest Cafe,"south indian, north indian, chinese",banashankari,3.5,10
518,518,0.542514,Vaishali Deluxe,"north indian, chinese",banashankari,3.8,42

In [43]:
df[
    ["name", "cuisines", "rest_type", "location", "restaurant_profile"]
].head()

,name,cuisines,rest_type,location,restaurant_profile
0,Jalsa,"north indian, mughlai, chinese",casual dining,banashankari,"north indian, mughlai, chinese casual dining b..."
1,Spice Elephant,"chinese, north indian, thai",casual dining,banashankari,"chinese, north indian, thai casual dining bana..."
2,San Churro Cafe,"cafe, mexican, italian","cafe, casual dining",banashankari,"cafe, mexican, italian cafe, casual dining ban..."
3,Addhuri Udupi Bhojana,"south indian, north indian",quick bites,banashankari,"south indian, north indian quick bites banasha..."
4,Grand Village,"north indian, rajasthani",casual dining,basavanagudi,"north indian, rajasthani casual dining basavan..."

In [44]:
print("Final dataset shape:", df.shape)
print("Remaining suspicious names:", len(bad_names))

Final dataset shape: (41226, 9)
Remaining suspicious names: 0

In [45]:
import os

os.makedirs("../dataset/engineered", exist_ok=True)

df.to_csv(
    "../dataset/engineered/zomato_engineered.csv",
    index=False,
    encoding="utf-8"
)

print("Engineered dataset saved successfully!")
print("Shape:", df.shape)

Engineered dataset saved successfully!
Shape: (41226, 9)

In [46]:
import os

file_path = "../dataset/engineered/zomato_engineered.csv"

print("File exists:", os.path.exists(file_path))

if os.path.exists(file_path):
    print(
        "File size:",
        round(os.path.getsize(file_path) / (1024 * 1024), 2),
        "MB"
    )

File exists: True
File size: 10.12 MB